### ISSUE TITLE
Parts list

### ISSUE THREAD

**Issue by wuhland** [CSSALTlab/Open_Source_Ventilator#21]
Is there a parts list available? If so it is not easy to find.

**Comment by MarshallRawson** [comment]
Take a look at out [operator's manual](https://cssaltlab.github.io/Open_Source_Ventilator/docs/OperatorsManual/manual.html) , it has the parts list for an operator's perspective. We are currently working on better docs, and a parts list will be coming soon. :)

**Comment by MarshallRawson** [comment]
see [our assembly instructions](https://cssaltlab.github.io/Open_Source_Ventilator/docs/electronics/assembly_instructions.html)
